/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1512639.petshop.GUI;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;

/**
 *
 * @author phamanhtuan
 */
public class NotifiacationPanel extends javax.swing.JFrame {

    /**
     * Creates new form NotifiacationPanel
     */
    public NotifiacationPanel() {
        initComponents();
        setLocationRelativeTo(null);

        ButtonOK.setBackground(new Color(237,37,100,10));
        buttonBackgroundPanel.setBackground(new Color(0,0,0,200));
        topBackgroundPanel.setBackground(new Color(231,37,100,200));
        SetAnimationForButton(ButtonOK,new Color(237,37,100,10));
        
    }

    private void SetAnimationForButton(JButton button,Color sourceColor)
    {
        button.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(e.getButton() == MouseEvent.BUTTON1){
                    button.setBackground(new Color(253,192,47,100));
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {
                if(e.getButton() == MouseEvent.BUTTON1){
                    button.setBackground(new Color(253,192,47,100));
                }
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                button.setBackground(new Color(137, 255, 254,10));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                button.setBackground(sourceColor);
            }
        });
    }
    
    public void SetNotificationText(String text){
        LabelNotification.setText(text);
    }    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonBackgroundPanel = new javax.swing.JPanel();
        ButtonOK = new javax.swing.JButton();
        LabelNotification = new javax.swing.JLabel();
        topBackgroundPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonBackgroundPanel.setForeground(new java.awt.Color(255, 255, 255));

        ButtonOK.setBackground(new java.awt.Color(255, 51, 153));
        ButtonOK.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ButtonOK.setForeground(new java.awt.Color(255, 255, 255));
        ButtonOK.setText("OK");
        ButtonOK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ButtonOK.setBorderPainted(false);
        ButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOKActionPerformed(evt);
            }
        });

        LabelNotification.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        LabelNotification.setForeground(new java.awt.Color(255, 255, 255));
        LabelNotification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNotification.setText("Tên tài khoản hoặc mật khẩu không chính xác");

        javax.swing.GroupLayout buttonBackgroundPanelLayout = new javax.swing.GroupLayout(buttonBackgroundPanel);
        buttonBackgroundPanel.setLayout(buttonBackgroundPanelLayout);
        buttonBackgroundPanelLayout.setHorizontalGroup(
            buttonBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonBackgroundPanelLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(ButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(LabelNotification, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
        buttonBackgroundPanelLayout.setVerticalGroup(
            buttonBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelNotification, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(buttonBackgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 440, 160));

        topBackgroundPanel.setBackground(new java.awt.Color(255, 102, 255));
        topBackgroundPanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOTIFICATION");

        javax.swing.GroupLayout topBackgroundPanelLayout = new javax.swing.GroupLayout(topBackgroundPanel);
        topBackgroundPanel.setLayout(topBackgroundPanelLayout);
        topBackgroundPanelLayout.setHorizontalGroup(
            topBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBackgroundPanelLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel2)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        topBackgroundPanelLayout.setVerticalGroup(
            topBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(17, 17, 17))
        );

        jPanel1.add(topBackgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1512639/petshop/notifiacationfinal.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOKActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_ButtonOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotifiacationPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotifiacationPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotifiacationPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotifiacationPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotifiacationPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonOK;
    private javax.swing.JLabel LabelNotification;
    private javax.swing.JPanel buttonBackgroundPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel topBackgroundPanel;
    // End of variables declaration//GEN-END:variables
}
