/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1512639_jdbc.View;

import javax.swing.JOptionPane;
import pkg1512639_jdbc.Define.Define;

/**
 *
 * @author phamanhtuan
 */
public class DatabaseInfor extends javax.swing.JFrame {

    /**
     * Creates new form DatabaseInfor
     */
    public DatabaseInfor() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        tfServername = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        lb2 = new javax.swing.JLabel();
        tfDatabasename = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        lb3 = new javax.swing.JLabel();
        tfPortnumber = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        lb4 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        lb5 = new javax.swing.JLabel();
        tfPassword = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnEnter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(7, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATABASE INFORMATION");
        jPanel2.add(jLabel1, "card2");

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb1.setBackground(new java.awt.Color(255, 0, 102));
        lb1.setForeground(new java.awt.Color(255, 255, 255));
        lb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb1.setText("SERVER NAME");
        lb1.setOpaque(true);
        jPanel3.add(lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 40));

        tfServername.setBackground(new java.awt.Color(255, 255, 255));
        tfServername.setForeground(new java.awt.Color(102, 102, 102));
        tfServername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfServername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        tfServername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfServernameActionPerformed(evt);
            }
        });
        jPanel3.add(tfServername, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 270, 40));

        jPanel1.add(jPanel3);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb2.setBackground(new java.awt.Color(255, 0, 102));
        lb2.setForeground(new java.awt.Color(255, 255, 255));
        lb2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb2.setText("DATABASE NAME");
        lb2.setAutoscrolls(true);
        lb2.setOpaque(true);
        jPanel9.add(lb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 40));

        tfDatabasename.setBackground(new java.awt.Color(255, 255, 255));
        tfDatabasename.setForeground(new java.awt.Color(102, 102, 102));
        tfDatabasename.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDatabasename.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel9.add(tfDatabasename, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 270, 40));

        jPanel1.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb3.setBackground(new java.awt.Color(255, 0, 102));
        lb3.setForeground(new java.awt.Color(255, 255, 255));
        lb3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb3.setText("PORT NUMBER");
        lb3.setOpaque(true);
        jPanel10.add(lb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 40));

        tfPortnumber.setBackground(new java.awt.Color(255, 255, 255));
        tfPortnumber.setForeground(new java.awt.Color(102, 102, 102));
        tfPortnumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPortnumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel10.add(tfPortnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 270, 40));

        jPanel1.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb4.setBackground(new java.awt.Color(255, 0, 102));
        lb4.setForeground(new java.awt.Color(255, 255, 255));
        lb4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb4.setText("USER NAME");
        lb4.setOpaque(true);
        jPanel11.add(lb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 40));

        tfUsername.setBackground(new java.awt.Color(255, 255, 255));
        tfUsername.setForeground(new java.awt.Color(102, 102, 102));
        tfUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel11.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 270, 40));

        jPanel1.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb5.setBackground(new java.awt.Color(255, 0, 102));
        lb5.setForeground(new java.awt.Color(255, 255, 255));
        lb5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb5.setText("PASSWORD");
        lb5.setOpaque(true);
        jPanel12.add(lb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 40));

        tfPassword.setBackground(new java.awt.Color(255, 255, 255));
        tfPassword.setForeground(new java.awt.Color(102, 102, 102));
        tfPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel12.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 270, 40));

        jPanel1.add(jPanel12);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnEnter.setBackground(new java.awt.Color(255, 153, 51));
        btnEnter.setForeground(new java.awt.Color(255, 255, 255));
        btnEnter.setText("ENTER");
        btnEnter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btnEnter.setContentAreaFilled(false);
        btnEnter.setOpaque(true);
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
        String serverName   = tfServername.getText();
        String databaseName = tfDatabasename.getText();
        String portNumber   = tfPortnumber.getText();
        String username     = tfUsername.getText();
        String password     = tfPassword.getText();
        
        Define.DatabaseInfor.SERVER_NAME = serverName;
        Define.DatabaseInfor.DATABASE_PORT_NUMBER = portNumber;
        Define.DatabaseInfor.DATABASE_NAME = databaseName;
        Define.DatabaseInfor.DATABASE_USER_NAME = username;
        Define.DatabaseInfor.DATABASE_PASSWORD = password;
        
        try {
            MainWindow mainWindow = new MainWindow(0);
            mainWindow.setVisible(true);
            this.dispose();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Database Information invalid");
        }
    }//GEN-LAST:event_btnEnterActionPerformed

    private void tfServernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfServernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfServernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatabaseInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatabaseInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatabaseInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatabaseInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatabaseInfor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JTextField tfDatabasename;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfPortnumber;
    private javax.swing.JTextField tfServername;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
