/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1512639_jdbc.View;

import com.toedter.calendar.JDateChooser;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import pkg1512639_jdbc.Controller.Driver;
import pkg1512639_jdbc.Controller.StudentsManagerment;
import pkg1512639_jdbc.Define.Define;
import pkg1512639_jdbc.Model.Student;

/**
 *
 * @author phamanhtuan
 */
public final class MainWindow extends javax.swing.JFrame {

    private boolean isChangingStudentBirthday;
    private boolean isChangingstudentNote;
    private boolean isChangingStudentName;
    
    
    private StudentsManagerment studentsManagerment = new StudentsManagerment();
    private Driver driver = new Driver(Define.DatabaseInfor.SERVER_NAME, 
                                       Define.DatabaseInfor.DATABASE_NAME,
                                       Define.DatabaseInfor.DATABASE_PORT_NUMBER,
                                       Define.DatabaseInfor.DATABASE_USER_NAME, 
                                       Define.DatabaseInfor.DATABASE_PASSWORD);
    
    private JLabel lblStudentBirthday = new JLabel();
    private JDateChooser dateChooser = new JDateChooser(new Date());
    
    private ImageIcon compledteImageIcon = null;
    private ImageIcon editImageIcon = null;
    
    private int currentStudentIndex;
    private Student currentStudentObject = null;
    /**
     * Creates new form main
     */
    public MainWindow(int _studentIndex) {
        
        
        compledteImageIcon =  new ImageIcon(getClass().getResource("/pkg1512639_jdbc/View/completed.png"));
        editImageIcon =  new ImageIcon(getClass().getResource("/pkg1512639_jdbc/View/edit2.png"));
        
        isChangingStudentBirthday = false;
        isChangingStudentName = false;
        isChangingstudentNote = false;
        
        lblStudentBirthday.setHorizontalAlignment(SwingConstants.CENTER);
        lblStudentBirthday.setVerticalAlignment(SwingConstants.CENTER);
        
        
        studentsManagerment.createListStudentsFromDatabase();
        initComponents();
        pnlStudentBirthday.add(lblStudentBirthday);
        tfNumberContacts.setText(studentsManagerment.listStudents.size() + " Contacts");
        this.setLocationRelativeTo(null);
        setColorLabelEvents(lbAddStudent);
        intiStartGui();
        if(studentsManagerment.listStudents.size() > 0){
            setMainStudentInforView(_studentIndex,studentsManagerment.listStudents);
        }
         
    }
    
    public void setlbAvartar(JLabel label,BufferedImage image,int size){

        label.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        int with = image.getWidth();
        //int height = image.getHeight();
        int x = with/size;
        BufferedImage roundedImage = RoundedImage.makeRoundedCorner(image, 300*x);
        ImageIcon icon = new ImageIcon(roundedImage);
        Image avartar = icon.getImage().getScaledInstance(size,size, Image.SCALE_DEFAULT) ;
        label.setIcon(new ImageIcon(avartar));
        
        //ImageIO.write(roundedImage, "png", new File("icon.rounded.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel37 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnListStudents = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel48 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        tfNumberContacts = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        tfSearchStudent = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        lbAddStudent = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jPanel50 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel56 = new javax.swing.JPanel();
        lblEditStudentNote = new javax.swing.JLabel();
        jPanel49 = new javax.swing.JPanel();
        jPanel51 = new javax.swing.JPanel();
        jPanel53 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taStudentNote = new javax.swing.JTextArea();
        jPanel32 = new javax.swing.JPanel();
        jPanel52 = new javax.swing.JPanel();
        jPanel54 = new javax.swing.JPanel();
        lbBirthaday = new javax.swing.JLabel();
        pnlStudentBirthday = new javax.swing.JPanel();
        jPanel55 = new javax.swing.JPanel();
        lblEditBirthday = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jPanel57 = new javax.swing.JPanel();
        tfStudentName = new javax.swing.JTextField();
        jPanel58 = new javax.swing.JPanel();
        lblEditStudentName = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        lbID = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        jPanel45 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel46 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        plAvartar = new javax.swing.JPanel();
        avartarPanel = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        lbAvartar = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        JPanel21 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(new java.awt.GridLayout(1, 4, 3, 3));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.BorderLayout(10, 2));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnListStudents.setBackground(new java.awt.Color(255, 255, 255));
        pnListStudents.setLayout(new java.awt.GridLayout(1000, 1, 10, 2));
        jScrollPane2.setViewportView(pnListStudents);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(465, 300));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(497, 30));
        jPanel8.setLayout(new java.awt.GridLayout(1, 5));

        jPanel47.setBackground(new java.awt.Color(255, 255, 255));
        jPanel47.setLayout(new java.awt.CardLayout());

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(246, 80, 126));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("CONTACTS");
        jPanel47.add(jLabel14, "card2");

        jPanel8.add(jPanel47);

        jPanel48.setBackground(new java.awt.Color(255, 255, 255));
        jPanel48.setLayout(new java.awt.CardLayout());

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("DASHBOARD");
        jPanel48.add(jLabel15, "card2");

        jPanel8.add(jPanel48);

        jPanel41.setBackground(new java.awt.Color(255, 255, 255));
        jPanel41.setLayout(new java.awt.CardLayout());

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("MESSAGES");
        jPanel41.add(jLabel16, "card2");

        jPanel8.add(jPanel41);

        jPanel3.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.GridLayout(3, 0));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(497, 200));
        jPanel9.setLayout(new java.awt.GridLayout(1, 2));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new java.awt.CardLayout());

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Students");
        jPanel13.add(jLabel2, "card2");

        jPanel9.add(jPanel13);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.CardLayout());

        tfNumberContacts.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        tfNumberContacts.setForeground(new java.awt.Color(153, 153, 153));
        tfNumberContacts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tfNumberContacts.setText("3.043 Contacts");
        jPanel12.add(tfNumberContacts, "card2");

        jPanel9.add(jPanel12);

        jPanel7.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(497, 50));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jPanel14.setBackground(new java.awt.Color(102, 204, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(350, 81));
        jPanel14.setLayout(new java.awt.GridLayout(2, 1));

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setLayout(new java.awt.CardLayout());

        tfSearchStudent.setForeground(new java.awt.Color(153, 153, 153));
        tfSearchStudent.setText("Search your students");
        tfSearchStudent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        tfSearchStudent.setSelectionColor(new java.awt.Color(204, 204, 204));
        tfSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchStudentActionPerformed(evt);
            }
        });
        tfSearchStudent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSearchStudentKeyPressed(evt);
            }
        });
        jPanel23.add(tfSearchStudent, "card2");

        jPanel14.add(jPanel23);

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel22);

        jPanel10.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(255, 51, 153));
        jPanel15.setLayout(new java.awt.GridLayout(2, 1));

        jPanel25.setBackground(new java.awt.Color(0, 204, 204));
        jPanel25.setLayout(new java.awt.CardLayout());

        lbAddStudent.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbAddStudent.setForeground(new java.awt.Color(255, 255, 255));
        lbAddStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAddStudent.setText("+ ADD STUDENT");
        lbAddStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAddStudentMouseClicked(evt);
            }
        });
        jPanel25.add(lbAddStudent, "card2");

        jPanel15.add(jPanel25);

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel24);

        jPanel10.add(jPanel15);

        jPanel7.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(509, 150));
        jPanel11.setLayout(new java.awt.GridLayout(2, 2));

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel26);

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel28);

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setPreferredSize(new java.awt.Dimension(254, 30));
        jPanel27.setLayout(new java.awt.GridLayout(1, 5));

        jPanel30.setBackground(new java.awt.Color(255, 255, 255));
        jPanel30.setLayout(new java.awt.CardLayout());
        jPanel27.add(jPanel30);

        jPanel31.setBackground(new java.awt.Color(255, 255, 255));
        jPanel31.setLayout(new java.awt.CardLayout());
        jPanel27.add(jPanel31);

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel29.setLayout(new java.awt.CardLayout());
        jPanel27.add(jPanel29);

        jPanel11.add(jPanel27);

        jPanel33.setBackground(new java.awt.Color(204, 255, 204));
        jPanel33.setPreferredSize(new java.awt.Dimension(254, 30));
        jPanel33.setLayout(new java.awt.CardLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1512639_jdbc/View/learning.png"))); // NOI18N
        jLabel5.setText("LIST STUDENTS");
        jLabel5.setOpaque(true);
        jPanel33.add(jLabel5, "card2");

        jPanel11.add(jPanel33);

        jPanel7.add(jPanel11);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new java.awt.BorderLayout(0, 2));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel36.setPreferredSize(new java.awt.Dimension(509, 50));
        jPanel36.setLayout(new java.awt.BorderLayout());

        jPanel50.setBackground(new java.awt.Color(255, 255, 255));
        jPanel50.setPreferredSize(new java.awt.Dimension(509, 50));
        jPanel50.setLayout(new javax.swing.BoxLayout(jPanel50, javax.swing.BoxLayout.LINE_AXIS));

        jPanel42.setBackground(new java.awt.Color(255, 255, 255));
        jPanel42.setPreferredSize(new java.awt.Dimension(400, 112));
        jPanel42.setLayout(new java.awt.CardLayout());

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 102));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1512639_jdbc/View/clipboard-with-pencil-.png"))); // NOI18N
        jLabel19.setText("NOTE");
        jPanel42.add(jLabel19, "card2");

        jPanel50.add(jPanel42);

        jPanel56.setBackground(new java.awt.Color(255, 255, 255));
        jPanel56.setLayout(new java.awt.CardLayout());

        lblEditStudentNote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditStudentNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1512639_jdbc/View/edit2.png"))); // NOI18N
        lblEditStudentNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditStudentNoteMouseClicked(evt);
            }
        });
        jPanel56.add(lblEditStudentNote, "card2");

        jPanel50.add(jPanel56);

        jPanel36.add(jPanel50, java.awt.BorderLayout.PAGE_START);

        jPanel49.setBackground(new java.awt.Color(255, 255, 255));
        jPanel49.setLayout(new javax.swing.BoxLayout(jPanel49, javax.swing.BoxLayout.X_AXIS));

        jPanel51.setBackground(new java.awt.Color(255, 255, 255));
        jPanel51.setPreferredSize(new java.awt.Dimension(80, 192));

        javax.swing.GroupLayout jPanel51Layout = new javax.swing.GroupLayout(jPanel51);
        jPanel51.setLayout(jPanel51Layout);
        jPanel51Layout.setHorizontalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel51Layout.setVerticalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel49.add(jPanel51);

        jPanel53.setBackground(new java.awt.Color(255, 255, 255));
        jPanel53.setLayout(new java.awt.CardLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        taStudentNote.setEditable(false);
        taStudentNote.setBackground(new java.awt.Color(255, 255, 255));
        taStudentNote.setColumns(20);
        taStudentNote.setForeground(new java.awt.Color(102, 102, 102));
        taStudentNote.setLineWrap(true);
        taStudentNote.setRows(100);
        taStudentNote.setText("What is Lorem Ipsum?\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.");
        taStudentNote.setWrapStyleWord(true);
        taStudentNote.setBorder(null);
        jScrollPane1.setViewportView(taStudentNote);

        jPanel53.add(jScrollPane1, "card2");

        jPanel49.add(jPanel53);

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setPreferredSize(new java.awt.Dimension(80, 192));

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel49.add(jPanel32);

        jPanel36.add(jPanel49, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel36, java.awt.BorderLayout.CENTER);

        jPanel52.setBackground(new java.awt.Color(255, 255, 255));
        jPanel52.setPreferredSize(new java.awt.Dimension(509, 50));
        jPanel52.setLayout(new javax.swing.BoxLayout(jPanel52, javax.swing.BoxLayout.LINE_AXIS));

        jPanel54.setBackground(new java.awt.Color(255, 255, 255));
        jPanel54.setPreferredSize(new java.awt.Dimension(200, 32));
        jPanel54.setLayout(new java.awt.CardLayout());

        lbBirthaday.setBackground(new java.awt.Color(255, 255, 255));
        lbBirthaday.setForeground(new java.awt.Color(102, 102, 102));
        lbBirthaday.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbBirthaday.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1512639_jdbc/View/birthday-cake (1).png"))); // NOI18N
        lbBirthaday.setText("BIRTHDAY :");
        lbBirthaday.setPreferredSize(new java.awt.Dimension(400, 32));
        jPanel54.add(lbBirthaday, "card2");

        jPanel52.add(jPanel54);

        pnlStudentBirthday.setBackground(new java.awt.Color(255, 255, 255));
        pnlStudentBirthday.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlStudentBirthday.setLayout(new java.awt.CardLayout());
        jPanel52.add(pnlStudentBirthday);

        jPanel55.setBackground(new java.awt.Color(255, 255, 255));
        jPanel55.setLayout(new java.awt.CardLayout());

        lblEditBirthday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditBirthday.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1512639_jdbc/View/edit2.png"))); // NOI18N
        lblEditBirthday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditBirthdayMouseClicked(evt);
            }
        });
        jPanel55.add(lblEditBirthday, "card2");

        jPanel52.add(jPanel55);

        jPanel5.add(jPanel52, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setPreferredSize(new java.awt.Dimension(497, 400));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel16.setBackground(new java.awt.Color(255, 0, 102));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new java.awt.GridLayout(2, 1));

        jPanel34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel34.setPreferredSize(new java.awt.Dimension(509, 40));
        jPanel34.setLayout(new javax.swing.BoxLayout(jPanel34, javax.swing.BoxLayout.LINE_AXIS));

        jPanel57.setBackground(new java.awt.Color(255, 255, 255));
        jPanel57.setPreferredSize(new java.awt.Dimension(450, 40));
        jPanel57.setLayout(new java.awt.CardLayout());

        tfStudentName.setEditable(false);
        tfStudentName.setBackground(new java.awt.Color(255, 255, 255));
        tfStudentName.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        tfStudentName.setForeground(new java.awt.Color(102, 102, 102));
        tfStudentName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfStudentName.setText("Phạm Anh Tuấn");
        tfStudentName.setBorder(null);
        tfStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStudentNameActionPerformed(evt);
            }
        });
        jPanel57.add(tfStudentName, "card2");

        jPanel34.add(jPanel57);

        jPanel58.setBackground(new java.awt.Color(255, 255, 255));
        jPanel58.setLayout(new java.awt.CardLayout());

        lblEditStudentName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditStudentName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1512639_jdbc/View/edit2.png"))); // NOI18N
        lblEditStudentName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditStudentNameMouseClicked(evt);
            }
        });
        jPanel58.add(lblEditStudentName, "card2");

        jPanel34.add(jPanel58);

        jPanel18.add(jPanel34);

        jPanel35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel35.setLayout(new java.awt.CardLayout());

        lbID.setBackground(new java.awt.Color(255, 255, 255));
        lbID.setForeground(new java.awt.Color(0, 0, 0));
        lbID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbID.setText("Student at university of siences");
        lbID.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel35.add(lbID, "card2");

        jPanel18.add(jPanel35);

        jPanel16.add(jPanel18, java.awt.BorderLayout.PAGE_START);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

        jPanel39.setBackground(new java.awt.Color(255, 255, 255));
        jPanel39.setPreferredSize(new java.awt.Dimension(130, 112));

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel39);

        jPanel40.setLayout(new java.awt.GridLayout(2, 0));

        jPanel44.setBackground(new java.awt.Color(255, 255, 255));
        jPanel44.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        jPanel45.setBackground(new java.awt.Color(255, 51, 102));
        jPanel45.setLayout(new java.awt.CardLayout());

        jLabel17.setBackground(new java.awt.Color(255, 51, 102));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1512639_jdbc/View/label.png"))); // NOI18N
        jLabel17.setBounds(new java.awt.Rectangle(0, 0, 10, 10));
        jLabel17.setOpaque(true);
        jPanel45.add(jLabel17, "card2");

        jPanel44.add(jPanel45);

        jPanel46.setBackground(new java.awt.Color(255, 153, 51));
        jPanel46.setLayout(new java.awt.CardLayout());

        jLabel12.setBackground(new java.awt.Color(255, 153, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1512639_jdbc/View/garbage (1).png"))); // NOI18N
        jLabel12.setOpaque(true);
        jPanel46.add(jLabel12, "card2");

        jPanel44.add(jPanel46);

        jPanel40.add(jPanel44);

        jPanel43.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel40.add(jPanel43);

        jPanel17.add(jPanel40);

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel38.setPreferredSize(new java.awt.Dimension(130, 70));

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel38);

        jPanel16.add(jPanel17, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel16, java.awt.BorderLayout.CENTER);

        plAvartar.setBackground(new java.awt.Color(255, 255, 255));
        plAvartar.setPreferredSize(new java.awt.Dimension(700, 250));
        plAvartar.setLayout(new java.awt.BorderLayout());

        avartarPanel.setBackground(new java.awt.Color(255, 255, 255));
        avartarPanel.setPreferredSize(new java.awt.Dimension(509, 300));
        avartarPanel.setLayout(new javax.swing.BoxLayout(avartarPanel, javax.swing.BoxLayout.LINE_AXIS));

        jPanel20.setOpaque(false);
        jPanel20.setPreferredSize(new java.awt.Dimension(130, 220));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        avartarPanel.add(jPanel20);

        jPanel19.setBackground(new java.awt.Color(255, 153, 0));
        jPanel19.setOpaque(false);
        jPanel19.setLayout(new java.awt.CardLayout());

        lbAvartar.setBackground(new java.awt.Color(153, 153, 153));
        lbAvartar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAvartar.setPreferredSize(new java.awt.Dimension(220, 220));
        lbAvartar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAvartarMouseClicked(evt);
            }
        });
        jPanel19.add(lbAvartar, "card2");

        avartarPanel.add(jPanel19);

        jPanel21.setOpaque(false);
        jPanel21.setPreferredSize(new java.awt.Dimension(130, 220));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        avartarPanel.add(jPanel21);

        plAvartar.add(avartarPanel, java.awt.BorderLayout.CENTER);

        JPanel21.setBackground(new java.awt.Color(255, 255, 255));
        JPanel21.setPreferredSize(new java.awt.Dimension(509, 30));
        JPanel21.setLayout(new java.awt.CardLayout());
        plAvartar.add(JPanel21, java.awt.BorderLayout.PAGE_START);

        jPanel6.add(plAvartar, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchStudentActionPerformed
        // TODO add your handling code here:
        String data = tfSearchStudent.getText();
        if(data == ""){
            createListViewStudents(studentsManagerment.listStudents);
        }
    }//GEN-LAST:event_tfSearchStudentActionPerformed

    private void lbAvartarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAvartarMouseClicked
        // TODO add your handling code here:
         if(evt.getButton() == MouseEvent.BUTTON1){
                    if(evt.getClickCount() >=2 ){
                        
                        //show open dialog:
                        JFileChooser fileChooser = new JFileChooser();
                        int chooser = fileChooser.showOpenDialog(null);
                        
                        if(chooser == JFileChooser.APPROVE_OPTION){
                            String url = fileChooser.getSelectedFile().toString();
                            try {
                                BufferedImage image = ImageIO.read(new File(url));
                                if(image == null){
                                }
                                else{
                                    Student currentStudent = studentsManagerment.listStudents.get(currentStudentIndex);
                                   setlbAvartar(lbAvartar,image,220);
                                    if(currentStudent != null){
                                        InputStream is = new FileInputStream(new File(url));
                                        currentStudent.setAvartar(is);
                                        driver.updateStudentAvartarByID(is, currentStudent.getId());
                                        
                                    }
                                    
                                }
                            }
                            catch (IOException ex) {Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);}
                            
                        }
                    }
                }
    }//GEN-LAST:event_lbAvartarMouseClicked

    private void lbAddStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAddStudentMouseClicked
        // TODO add your handling code here:
        StudentInforEditWindow studentInforEditWindow = new StudentInforEditWindow();
        studentInforEditWindow.setLocationRelativeTo(null);
        studentInforEditWindow.setVisible(true);
        
        studentInforEditWindow.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                super.windowClosed(e); //To change body of generated methods, choose Tools | Templates.
                    studentsManagerment = null;
                    studentsManagerment = new StudentsManagerment();
                    studentsManagerment.createListStudentsFromDatabase();
                    createListViewStudents(studentsManagerment.listStudents);
                }
            
        });
    }//GEN-LAST:event_lbAddStudentMouseClicked

    private void tfSearchStudentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchStudentKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String data = tfSearchStudent.getText();
            if(data.equals("")){
                createListViewStudents(studentsManagerment.listStudents);
               
            }
            
 
            List<Student> students ;
            if(Character.isDigit(data.toCharArray()[0])){
               students =   researchListStudent(data, Define.ResearchType.STUDENT_ID);
            }
            else{
                students = researchListStudent(data, Define.ResearchType.STUDENT_NAME);
            }
            
            //System.out.println("SIZE = " + students.size());
            //System.out.println("NAME 0" + students.get(0).getName());
            
            if(students.size() > 0){
                createListViewStudents(students);
            }
            else{
                createListViewStudents(studentsManagerment.listStudents);
            }
        }
    }//GEN-LAST:event_tfSearchStudentKeyPressed

    private void lblEditBirthdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditBirthdayMouseClicked
        // TODO add your handling code here:
        if(isChangingStudentBirthday == false){
            if(evt.getButton() == MouseEvent.BUTTON1){
                lblEditBirthday.setIcon(compledteImageIcon);
                pnlStudentBirthday.removeAll();
                pnlStudentBirthday.revalidate();
                pnlStudentBirthday.repaint();

                pnlStudentBirthday.add(dateChooser);
                isChangingStudentBirthday = true;
            }
        }
        else if(isChangingStudentBirthday == true){  
            if(evt.getButton() == MouseEvent.BUTTON1){
                
                lblEditBirthday.setIcon(editImageIcon);
                Date studentBirthday = (Date) dateChooser.getDate();
                DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                String strDate = df.format(studentBirthday);      
                java.sql.Date newDate = java.sql.Date.valueOf(strDate);
                driver.updateStudentBirthdayByID(newDate,currentStudentObject.getId());               
                lblStudentBirthday.setText(strDate);
               
                pnlStudentBirthday.removeAll();
                pnlStudentBirthday.revalidate();
                pnlStudentBirthday.repaint();
                pnlStudentBirthday.add(lblStudentBirthday);
                isChangingStudentBirthday = false;
                studentsManagerment.createListStudentsFromDatabase();
                createListViewStudents(studentsManagerment.listStudents);
            }
        }
    }//GEN-LAST:event_lblEditBirthdayMouseClicked

    private void lblEditStudentNoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditStudentNoteMouseClicked
        // TODO add your handling code here:
        if(evt.getButton() == MouseEvent.BUTTON1){
            if(isChangingstudentNote == false){
                lblEditStudentNote.setIcon(compledteImageIcon);
                taStudentNote.setEditable(true);
                isChangingstudentNote = true;
            }
            else{
                lblEditStudentNote.setIcon(editImageIcon);
                String content = taStudentNote.getText();
                driver.updateStudentNoteByID(content, currentStudentObject.getId());
                taStudentNote.setEditable(false);
                isChangingstudentNote = false;
                studentsManagerment.createListStudentsFromDatabase();
                createListViewStudents(studentsManagerment.listStudents);

                
            }
        }
    }//GEN-LAST:event_lblEditStudentNoteMouseClicked

    private void tfStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStudentNameActionPerformed

    private void lblEditStudentNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditStudentNameMouseClicked
        // TODO add your handling code here:
        if(evt.getButton() == MouseEvent.BUTTON1){
            if(isChangingStudentName == false){
                lblEditStudentName.setIcon(compledteImageIcon);
                tfStudentName.setEditable(true);
                isChangingStudentName = true;
                
            }
            else{
                
                lblEditStudentName.setIcon(editImageIcon);
                tfStudentName.setEditable(false);
                String newName = tfStudentName.getText();
                driver.updateStudentNameByID(newName, currentStudentObject.getId());
                isChangingStudentName = false;
                studentsManagerment.createListStudentsFromDatabase();
                createListViewStudents(studentsManagerment.listStudents);
            }
        }
    }//GEN-LAST:event_lblEditStudentNameMouseClicked

    private void setColorLabelEvents(JLabel inputLabel){
        inputLabel.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                inputLabel.setForeground(new Color(252,68,130));
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                inputLabel.setForeground(Color.WHITE);
            }
        });
        
    }
    
    
    public void intiStartGui(){
        createListViewStudents(studentsManagerment.listStudents);
        
    }
    private void createListViewStudents(List<Student> listStudents){
        pnListStudents.removeAll();
        pnListStudents.revalidate();
        pnListStudents.repaint();
        
        
        int numberStudents = listStudents.size();
        for(int studentIndex = 0; studentIndex < numberStudents; studentIndex++){
            
            JPanel panel = new JPanel(new GridLayout(1,Define.NUMBER_SUB_PANEL_ITEM));
            panel.setName(studentIndex + "");
            Color bacgroundColor = new Color(180, 235, 241);
            Color textColor = Color.GRAY;
            
            if(studentIndex % 2 != 0){
                bacgroundColor = new Color(179, 223, 219);
                textColor = Color.WHITE;
            }
            
            //panel.setBackground(bacgroundColor);
            panel.setBackground(bacgroundColor);
            
            panel.addMouseListener(new MouseListener() {
                
                
                @Override
                public void mouseClicked(MouseEvent e) {
                   
                    Component panel = (Component)e.getSource();
                    int studentIndex =  Integer.parseInt(panel.getName()); 
                    setMainStudentInforView(studentIndex,listStudents);
                }

                @Override
                public void mousePressed(MouseEvent e) {
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                }

                @Override
                public void mouseExited(MouseEvent e) {
                }
            });
            panel.setPreferredSize(new Dimension(500, 40));
            ((GridLayout)panel.getLayout()).setHgap(10);
            
            JPanel []listSubPanel = new JPanel[Define.NUMBER_SUB_PANEL_ITEM];
            for(int panelIndex = 0; panelIndex <  Define.NUMBER_SUB_PANEL_ITEM; panelIndex++){
                listSubPanel[panelIndex] = new JPanel(new CardLayout());
                listSubPanel[panelIndex].setBackground(bacgroundColor);
                
            }
            
            JLabel lbStudentName,lbStudentID,lbSubAvartar,lbType;
            
            lbStudentName = new JLabel(listStudents.get(studentIndex).getName());
            lbStudentName.setForeground(textColor);
            lbStudentName.setHorizontalAlignment(JLabel.CENTER);
            lbStudentName.setVerticalAlignment(JLabel.CENTER);
           
            lbStudentID = new JLabel(listStudents.get(studentIndex).getId()+"");
            lbStudentID.setForeground(textColor);
            lbStudentID.setHorizontalAlignment(JLabel.CENTER);
            lbStudentID.setVerticalAlignment(JLabel.CENTER); 

            lbSubAvartar = new JLabel();
            lbSubAvartar.setHorizontalAlignment(JLabel.CENTER);
            lbSubAvartar.setVerticalAlignment(JLabel.CENTER);
            
            lbType = new JLabel(" Student");
            lbType.setOpaque(true);
            lbType.setBackground(new Color(241, 143, 94));
            lbType.setHorizontalAlignment(JLabel.CENTER);
            lbType.setVerticalAlignment(JLabel.CENTER);
            lbType.setForeground(Color.WHITE);
            
            if(listStudents.get(studentIndex).getAvartar() == null){
                
                
                try {
                    //String path = getClass().getClassLoader().getResource("").toString();
                    
                    String path = getClass().getResource("/pkg1512639_jdbc/View/avartar.jpg").getFile();
                    
                    BufferedImage image = ImageIO.read(new File(path));
                    setlbAvartar(lbSubAvartar, image, 30);
                } catch (IOException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                BufferedImage image = driver.getStudentAvartarByID(listStudents.get(studentIndex).getId());
                setlbAvartar(lbSubAvartar, image, 30);
                
            }
            
            listSubPanel[0].add(lbSubAvartar);
            listSubPanel[1].add(lbStudentID);
            listSubPanel[2].add(lbStudentName);
            listSubPanel[3].add(lbType);
            
            
            
            for(int panelIndex = 0; panelIndex < Define.NUMBER_SUB_PANEL_ITEM; panelIndex++){
                panel.add(listSubPanel[panelIndex]);
            }
            
            
            
        
            pnListStudents.add(panel);
        }
    }
    
    public void setMainStudentInforView(int studentIndex,List<Student> students){
        
        Student student = students.get(studentIndex);
        BufferedImage avartar = Driver.getInstance().getStudentAvartarByID(student.getId());
        
        lbID.setText(student.getId() + "");
        tfStudentName.setText(student.getName());
        lblStudentBirthday.setText(student.getBirthday().toString());
        taStudentNote.setText(student.getNote());
        currentStudentIndex = studentIndex;
        currentStudentObject = students.get(currentStudentIndex);
        
        if(avartar != null){
            setlbAvartar(lbAvartar, avartar, 220);
        }
        else{
            try {
                
                String path = getClass().getResource("/pkg1512639_jdbc/View/avartar.jpg").getFile();
                BufferedImage image = ImageIO.read(new File(path));
                setlbAvartar(lbAvartar, image, 220);
            
            } catch (IOException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow(0).setVisible(true);
            }
        });
    }

    //the function for create the action seach student in list student for the currentt list student
    //The values return is the a Student have type Student 
    //Example : 
    //        Write some thing in here : ....
    public  <T> List<Student> researchListStudent(T inputData, Define.ResearchType typeOfResearch){
        List<Student> listStudent = new ArrayList<>();
        int numberStudents = studentsManagerment.listStudents.size();
        
        switch(typeOfResearch){
            case STUDENT_NAME :{
                String studentName = (String)inputData;
                for(int studentIndex = 0; studentIndex < numberStudents; studentIndex++){
                    Student student = studentsManagerment.listStudents.get(studentIndex);
                    
                    if(student.getName().contains(studentName)){
                        listStudent.add(student);
                    }
                }
                break;
            }
            
            case STUDENT_ID :{
                
                String studentID = (String)inputData;
                for(int studentIndex = 0; studentIndex < numberStudents; studentIndex++){
                    Student student = studentsManagerment.listStudents.get(studentIndex);
                    String currentStudentID = student.getId() + "";
                    if(currentStudentID.contains(studentID)){
                        listStudent.add(student);
                    }
                    
                }
               
                break;
            }
            
            default: break;
        }
        
        return listStudent;
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel21;
    private javax.swing.JPanel avartarPanel;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAddStudent;
    private javax.swing.JLabel lbAvartar;
    public javax.swing.JLabel lbBirthaday;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lblEditBirthday;
    private javax.swing.JLabel lblEditStudentName;
    private javax.swing.JLabel lblEditStudentNote;
    private javax.swing.JPanel plAvartar;
    private javax.swing.JPanel pnListStudents;
    private javax.swing.JPanel pnlStudentBirthday;
    public javax.swing.JTextArea taStudentNote;
    private javax.swing.JLabel tfNumberContacts;
    private javax.swing.JTextField tfSearchStudent;
    private javax.swing.JTextField tfStudentName;
    // End of variables declaration//GEN-END:variables
}
