/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1512639_jdbc.View;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import pkg1512639_jdbc.Controller.Driver;
import pkg1512639_jdbc.Model.Student;

/**
 *
 * @author phamanhtuan
 */
public class StudentInforEditWindow extends javax.swing.JFrame {

    public boolean  isDisposed = false;
    /**
     * Creates new form StudentInforEditWindow
     */
    public StudentInforEditWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        label = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        tfID = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        tfName = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jdcBirthday = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taNote = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        lbImagePath = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        tfAvatarLink = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(7, 0));

        label.setBackground(new java.awt.Color(255, 255, 255));
        label.setLayout(new java.awt.CardLayout());

        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STUDENT INFORMATION");
        label.add(jLabel1, "card2");

        jPanel1.add(label);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jPanel12.setBackground(new java.awt.Color(255, 204, 204));
        jPanel12.setPreferredSize(new java.awt.Dimension(125, 59));
        jPanel12.setLayout(new java.awt.CardLayout());

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID");
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel12.add(jLabel2, "card2");

        jPanel3.add(jPanel12);

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel11.setLayout(new java.awt.CardLayout());

        tfID.setBackground(new java.awt.Color(255, 255, 255));
        tfID.setForeground(new java.awt.Color(51, 51, 51));
        tfID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfID.setText("ENTER ID");
        jPanel11.add(tfID, "card2");

        jPanel3.add(jPanel11);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jPanel14.setBackground(new java.awt.Color(255, 153, 153));
        jPanel14.setPreferredSize(new java.awt.Dimension(150, 100));
        jPanel14.setLayout(new java.awt.CardLayout());

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NAME");
        jPanel14.add(jLabel3, "card2");

        jPanel4.add(jPanel14);

        jPanel13.setLayout(new java.awt.CardLayout());

        tfName.setBackground(new java.awt.Color(255, 255, 255));
        tfName.setForeground(new java.awt.Color(51, 51, 51));
        tfName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });
        jPanel13.add(tfName, "card2");

        jPanel4.add(jPanel13);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jPanel16.setBackground(new java.awt.Color(255, 204, 204));
        jPanel16.setLayout(new java.awt.CardLayout());

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BIRTHDAY");
        jPanel16.add(jLabel4, "card2");

        jPanel5.add(jPanel16);

        jdcBirthday.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jdcBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdcBirthday, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel15);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jPanel18.setBackground(new java.awt.Color(255, 153, 153));
        jPanel18.setLayout(new java.awt.CardLayout());

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("NOTE");
        jPanel18.add(jLabel5, "card2");

        jPanel6.add(jPanel18);

        jPanel17.setLayout(new java.awt.CardLayout());

        taNote.setColumns(20);
        taNote.setRows(5);
        jScrollPane2.setViewportView(taNote);

        jPanel17.add(jScrollPane2, "card2");

        jPanel6.add(jPanel17);

        jPanel1.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jPanel20.setBackground(new java.awt.Color(255, 204, 204));
        jPanel20.setLayout(new java.awt.CardLayout());

        lbImagePath.setForeground(new java.awt.Color(51, 51, 51));
        lbImagePath.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImagePath.setText("CHOSSE AVARTAR");
        jPanel20.add(lbImagePath, "card2");

        jPanel7.add(jPanel20);

        jPanel19.setLayout(new java.awt.CardLayout());

        tfAvatarLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfAvatarLinkMouseClicked(evt);
            }
        });
        tfAvatarLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAvatarLinkActionPerformed(evt);
            }
        });
        jPanel19.add(tfAvatarLink, "card2");

        jPanel7.add(jPanel19);

        jPanel1.add(jPanel7);

        jPanel2.setLayout(new java.awt.GridLayout(1, 3));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.CardLayout());

        jButton1.setBackground(new java.awt.Color(255, 0, 102));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("ENTER");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton1, "card2");

        jPanel2.add(jPanel10);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8);

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        InputStream  studentAvartar   =  null;
        try {
            // TODO add your handling code here:
            int  studentID   =  Integer.parseInt(tfID.getText());
            String studentName = tfName.getText();
            String studentAvartarPath = tfAvatarLink.getText();
            
           
            studentAvartar = new FileInputStream(new File(studentAvartarPath));
            
            Date studentBirthday = (Date) jdcBirthday.getDate();
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String strDate = df.format(studentBirthday);
            java.sql.Date newDate = java.sql.Date.valueOf(strDate);
            
            String studentNote = taNote.getText();
            
            Student student =  new Student(studentID, studentName, newDate, studentNote, studentAvartar);
            System.out.println(studentName);
            Driver.getInstance().insertAStudent(student);
            this.dispose();

            isDisposed = true;

        } 
        catch (FileNotFoundException ex) {Logger.getLogger(StudentInforEditWindow.class.getName()).log(Level.SEVERE, null, ex);}
        finally 
        {
            try {   studentAvartar.close();} 
            catch (IOException ex) {Logger.getLogger(StudentInforEditWindow.class.getName()).log(Level.SEVERE, null, ex);}
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void tfAvatarLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAvatarLinkActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_tfAvatarLinkActionPerformed

    private void tfAvatarLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfAvatarLinkMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int chooser = fileChooser.showOpenDialog(null);
        
        if(chooser == JFileChooser.APPROVE_OPTION){
            String path = fileChooser.getSelectedFile().toString();
            tfAvatarLink.setText(path);
        }
    }//GEN-LAST:event_tfAvatarLinkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInforEditWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInforEditWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInforEditWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInforEditWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentInforEditWindow().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private com.toedter.calendar.JDateChooser jdcBirthday;
    private javax.swing.JPanel label;
    private javax.swing.JLabel lbImagePath;
    private javax.swing.JTextArea taNote;
    private javax.swing.JTextField tfAvatarLink;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
